### ISSUE TITLE
Bulid Menu dissapiering after tried adding more units to the game.

### ISSUE THREAD

**Issue by Lacc1986** [gammata/TA-Unofficial-Patch-Install#18]
In certain factories the building menu just dissapiers after i tried like this:

[MENUENTRY1]
	{
	UNITMENU=ARMAAP;
	**MENU=11; (or looks like if its more than 7 in certain factories or bulider units)**
	BUTTON=5;
	UNITNAME=A10T2;
	}

Is this an alredy known issue or is there any way to fix it?

**Comment by Lacc1986** [comment]
Just find the way to extend unitmenus by myself. I added:

MenuExtension = 15;

; Menu Extension
; Set to the maximum number of menu pages you want to use
; Default is 7

to Settings.INI file.

**Comment by Lacc1986** [comment]
However, after I tested out the game further I noticed a bug is present in the code that prevent me to allow MenuExtension for Construction units like Adv. Construction Aircraft. Is there any way this can be patched or any way to work around it?

I applied:

AdvConstructionAircraftMenuExtension = 10;

; Adv Construction Aircraft Menu Extension
; Set to the maximum number of menu pages for the Adv Construction Aircraft
; Default is 7

But this is not working as the previous fix intends to do so. Thank you for looking into this.

**Comment by Lacc1986** [comment]
However, after I tested out the game further I noticed a bug is present in the code that prevent me to allow MenuExtension for Construction units like Adv. Construction Aircraft. Is there any way this can be patched or any way to work around it?

I applied:

AdvConstructionAircraftMenuExtension = 10;

; Adv Construction Aircraft Menu Extension
; Set to the maximum number of menu pages for the Adv Construction Aircraft
; Default is 7

But this is not working as the previous fix intends to do so. Thank you for looking into this.

**Comment by Lacc1986** [comment]
Just a bit of a correction: The code above allows me to extend the menus for all units to 15 but it won't loop back to page 2 after I reach page 15 for example. Any way to overcome this bug?

**Comment by gammata** [comment]
This is a modding issue and completely unrelated to the patch. This is not the place to ask for help for your modding of content for the game.

If you want help with this, post on https://www.tauniverse.com/forum/ under Modding, Maps and Units, or visit the discord https://discord.gg/Z4hJpVbmyW and post in #help.
