### ISSUE TITLE
DMCA Takedown

### ISSUE THREAD

**Issue by ghost** [gammata/TA-Unofficial-Patch-Install#22]
I am Thaldren.

Substantial portions of my work are present in the contents of this repository.

Take down this repository in its entirety or face legal action.

**Comment by gammata** [comment]
Your work is not copyrighted. Furthermore very little of it is your work. You rewrote what was already there.

**Comment by gammata** [comment]
Your work is not copyrighted. Furthermore very little of it is your work. You rewrote what was already there. 

You are banned and prevented from contributing further in any TA projects due to toxic, threatening and illegal behaviour.
