### ISSUE TITLE
Observer issue when playing on TAF 

### ISSUE THREAD

**Issue by ageekhere** [gammata/TA-Unofficial-Patch-Install#9]
Was playing on TAF and it seems that players could not observe/watch the game when someone has the patch installed.

**Comment by gammata** [comment]
Unable to replicate, we are all using the patch and watching is not problematic at all.

**Comment by ageekhere** [comment]
Will play a few move games to see if the issue comes up again, note it could be that some players on TAF are not using the patch.

**Comment by gammata** [comment]
For TAF issues go here https://github.com/ta-forever/downlords-taf-client/issues
